### PR TITLE
30 gig update gig functionailty

### LINKED ISSUE #30: Gig: Update Gig Functionailty
Venue entered wrong information into the Gig form and wants to be able to edit the gig.
- Venue wants to enter bands into the band list
- Venue wants to be able to change any information previously entered

### PR DESCRIPTION
**Pull request by mmcadoulos**
- Added PutMapping in GigController
- Added Edit Gig Form. Number of Bandslots are unchangeable right now (but left commented code for future reference)
- Added button in VenueUserDashboard to navigate to edit gig
- Changed the styling of delete gig button to provide more contrast
- Added editGig function in GigService.jsx

### CODE REVIEW

**Review by ayjsh — COMMENTED** [review]
When I ran it on my machine, I didn't put it an opening act or supporting act and it didn't give me the option to add them when editing. Is that what the commented out section is at line 149?

**Comment by mmcadoulos** [comment]
> When I ran it on my machine, I didn't put it an opening act or supporting act and it didn't give me the option to add them when editing. Is that what the commented out section is at line 149?

Sorry only just now seeing this. Yes currently I have not figured out how to get that portion working on the edit form so I have just set it to keep whatever was previously entered for the number of band slots. I figured it will be better to have a mostly functioning edit form rather than not having one.

**Review by ayjsh — DISMISSED** [review]
Approving!

**Review by arevathi125 — APPROVED** [review]
Everything looks and working good

**Pull request merged**
